### ISSUE TITLE
Not compatible with the latest version of AssemblyScript

### ISSUE THREAD

**Issue by JairusSW** [gagdiez/serial-as#36]
Hello, @gagdiez!
Just wanted to note that `@serial-as/json` is not compatible with AssemblyScript `0.20.x`.
@jtenner updated `visitor-as`, so that can be dropped in along with ESM integration

**Comment by gagdiez** [comment]
Hi @JairusSW, sadly enough, as the rest of the community I am stuck waiting the update of as-pect. I see that some progress is being made in their repository, but still, there are some errors that do not allow me to advance.

Hopefully, we will be able to solve them soon.

Best,
Guillermo.

**Comment by jtenner** [comment]
> Hi @JairusSW, sadly enough, as the rest of the community I am stuck waiting the update of as-pect. I see that some progress is being made in their repository, but still, there are some errors that do not allow me to advance.
> 
> Hopefully, we will be able to solve them soon.
> 
> Best, Guillermo.

Hey Guillermo, do you think I can help you upgrade your as-pect version (since the work is done?)

**Comment by jtenner** [comment]
> Hi @JairusSW, sadly enough, as the rest of the community I am stuck waiting the update of as-pect. I see that some progress is being made in their repository, but still, there are some errors that do not allow me to advance.
> 
> Hopefully, we will be able to solve them soon.
> 
> Best, Guillermo.

Actually, can we chat today? I don't know if you have discord, but I'm in the assemblyscript discord and I would love to submit a pull request with all the changes needed.

**Comment by JairusSW** [comment]
@gagdiez. @jtenner here updated as-pect and visitor-as meaning that all the existing libraries are there waiting to be used
:D
Best of luck!

**Comment by gagdiez** [comment]
@jtenner thank you so much, version 2.0.0 has been released
