### ISSUE TITLE
Encoding and decoding decorators should be separated

### ISSUE THREAD

**Issue by yjhmelody** [gagdiez/serial-as#4]

**Comment by willemneal** [comment]
My thoughts are to make a new `derive` macro so you can specify `derive(Serializable, Deserializable)`.

**Comment by yjhmelody** [comment]
> My thoughts are to make a new `derive` macro so you can specify `derive(Serializable, Deserializable)`.

That's bad. It's not `rust`. It is bad to use a commonly used name, I should have proposed to change it to the form of <library name>.<interface>. There is a namespace to reduce future conflicts.

**Comment by yjhmelody** [comment]
For example, for performance considerations, users need to automatically implement decode/manually implement encode, or the encoding value of type A needs to be decoded with type B.

**Comment by gagdiez** [comment]
The user can still do that. The enc/decoding is handled by a separate object, so B can implement its own version of a decoder.

The decorator only makes the object explain how it is encoded, therefore, it MUST explain how it should be decoded. Otherwise an inconsistency will be created.
